import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@repo/ui/Toaster"
import { Navbar } from "../../components/Navbar"
import { SessionProvider } from "@repo/ui/SessionProvider"
import { disable2fa } from "../../lib/twoFA"
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} bg-[#f2f1f5] ${geistMono.variable}`}>
        <SessionProvider>
          <NextIntlClientProvider messages={messages} locale={locale}>
            <Navbar disable2fa={disable2fa} />
            {children}
            <Toaster />
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
