import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@repo/ui/Toaster"
import { Navbar } from "../../components/Navbar"
import { SessionProvider } from "@repo/ui/SessionProvider"
import { disable2fa } from "../../lib/twoFA"
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { isMasterKeyActiveAndVerified } from '../../lib/masterkey'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Kraken | Fast, secure & easy digital e-wallet. Send & receive money instantly.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages()
  const maserKeyVerificationStatus = await isMasterKeyActiveAndVerified()
  console.log(maserKeyVerificationStatus);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} bg-[#F6F5F9] ${geistMono.variable} relative overflow-x-hidden`}>
        <SessionProvider>
          <NextIntlClientProvider messages={messages} locale={locale}>
            <Navbar disable2fa={disable2fa} maserKeyVerificationStatus={maserKeyVerificationStatus} />
            {children}
            <Toaster />
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
